/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 GranAromaDeluxe.glb --transform
*/
// @ts-nocheck

import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default forwardRef(function GranAromaDeluxe(props, ref) {
  const { nodes, materials } = useGLTF('models/GranAromaDeluxe.glb')

  materials.GranAroma_deluxe.map = null;
  materials.GranAroma_deluxe.metalnessMap = null;
  materials.GranAroma_deluxe.roughnessMap = null;
  materials.GranAroma_deluxe.normalMap = null;

  return (
    <group
      ref={ref}
      position-z={-0.05}
      {...props}
      dispose={null}
    >
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Block_01013.geometry} material={materials.GranAroma_deluxe} />
        <mesh castShadow receiveShadow geometry={nodes.Block_01013_1.geometry} material={materials['Transparent plastic.003']} />
        <mesh geometry={nodes.Block_01013_2.geometry} material={materials.black} />
        <mesh geometry={nodes.Block_01013_3.geometry} material={materials['milk container label.002']} />
        <mesh receiveShadow geometry={nodes.Block_01013_4.geometry} material={materials['milk.002']} />
      </group>
    </group>
  )
})

useGLTF.preload('/models/GranAromaDeluxe.glb')
