// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 XelsisSuprema.glb --transform
*/

import { Html, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { forwardRef, useRef } from 'react'

import type { Ref } from 'react'
import type { Group } from 'three'
import { subscribe } from 'valtio'

const Model = forwardRef(function XelsisSuprema(props, ref: Ref<Group>) {

  const { nodes, materials } = useGLTF('models/XelsisSuprema.glb')

  const screenRef = useRef<HTMLDivElement>(null);
  const drinksRef = useRef<HTMLDivElement>(null);

  const unsubscribe = subscribe(props.state, () => {
    if (props.active) {
      materials['Xelsis suprema.002'].color.set(props.state.color ? props.state.color : 'white')
    }
  })

  useFrame(({ camera }) => {
    if (screenRef.current && drinksRef.current) {
      if (props.active && camera.position.y < 0.40) {
        screenRef.current.classList.remove('translate-y-2');
        screenRef.current.classList.remove('opacity-0');

        drinksRef.current.classList.remove('translate-y-2');
        drinksRef.current.classList.remove('opacity-0');

        screenRef.current.classList.add('translate-y-0');
        screenRef.current.classList.add('opacity-100');

        drinksRef.current.classList.add('translate-y-0');
        drinksRef.current.classList.add('opacity-100');
      } else {
        screenRef.current.classList.remove('translate-y-0');
        screenRef.current.classList.remove('opacity-100');

        drinksRef.current.classList.remove('translate-y-0');
        drinksRef.current.classList.remove('opacity-100');

        screenRef.current.classList.add('translate-y-2');
        screenRef.current.classList.add('opacity-0');

        drinksRef.current.classList.add('translate-y-2');
        drinksRef.current.classList.add('opacity-0');
      }
    }
  })

  return (
    <group
      {...props}
      dispose={null}
      ref={ref}
    >
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh rotation-x={-Math.PI / 2}>
          <Html scale={0.04} position={[0.2, 0.15, 0.18]} transform occlude>
            <div ref={drinksRef} className="items-center px-4 py-2 text-xs rounded-full opacity-0 delay-150 duration-500 translate-y-2 transition-all text-slate-300 bg-slate-50/70">
              <span className="text-brown-dark/70">22 Drinks</span>
            </div>
          </Html>
        </mesh>
        <mesh rotation-x={-Math.PI / 2}>
          <Html scale={0.04} position={[0.05, 0.4, 0.2]} transform occlude>
            <div ref={screenRef} className="items-center px-4 py-2 text-xs rounded-full opacity-0 delay-150 duration-500 translate-y-2 transition-all text-slate-300 bg-slate-50/70">
              <span className="text-brown-dark/70">7.84&quot; Screen</span>
            </div>
          </Html>
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.Block_01006_2.geometry} material={materials['Xelsis suprema.002']} />
        <mesh castShadow receiveShadow geometry={nodes.Block_01006_3.geometry} material={materials['Transparent plastic.002']} />
        <mesh receiveShadow geometry={nodes.Block_01006_4.geometry} material={materials.milk} />
        <mesh geometry={nodes.Block_01006_1.geometry} material={materials['milk container label']} />
        <mesh geometry={nodes.Block_01006.geometry} material={materials['black ']} />
        <mesh castShadow receiveShadow geometry={nodes.Block_01006_5.geometry} material={materials['reservoir lid']} />
      </group>
    </group>
  )
})

export default Model

useGLTF.preload('/models/XelsisSuprema.glb')
