/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 XelsisDeluxe.glb --transform
*/

// @ts-nocheck
//
import { useGLTF } from '@react-three/drei'
import { forwardRef } from 'react'

export default forwardRef(function XelsisDeluxe(props, ref) {
  const { nodes, materials } = useGLTF('models/XelsisDeluxe.glb')

  materials['Xelsis Deluxe.003'].map = null;
  materials['Xelsis Deluxe.003'].metalnessMap = null;
  materials['Xelsis Deluxe.003'].roughnessMap = null;
  materials['Xelsis Deluxe.003'].normalMap = null;

  return (
    <group
      ref={ref}
      // position-z={-0.05}
      {...props}
      dispose={null}
    >
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Xelsis_20_CAD___WORKING_v1009.geometry} material={materials['Xelsis Deluxe.003']} />
        <mesh castShadow receiveShadow geometry={nodes.Xelsis_20_CAD___WORKING_v1009_1.geometry} material={materials['Transparent plastic.001']} />
        <mesh receiveShadow geometry={nodes.Xelsis_20_CAD___WORKING_v1009_2.geometry} material={materials['milk.001']} />
        <mesh geometry={nodes.Xelsis_20_CAD___WORKING_v1009_3.geometry} material={materials['milk container label.001']} />
        <mesh geometry={nodes.Xelsis_20_CAD___WORKING_v1009_4.geometry} material={materials['black .001']} />
        <mesh castShadow receiveShadow geometry={nodes.Xelsis_20_CAD___WORKING_v1009_5.geometry} material={materials['reservoir lid.001']} />
      </group>
    </group>
  )
})

useGLTF.preload('/models/XelsisDeluxe.glb')

